#
# Test that all unpublished input data were copied by user to this directory.
# If some of them are missing, fail.
#
# Author:  Karel Brinda <kbrinda@hsph.harvard.edu>
#
# License: MIT
#

.PHONY: test

include ../*.mk

all: test

test: ## Check if all files are present


cleanall: clean

